version: '3.3'
services:

    nginx:
        image: nginx
        container_name: nginx
        ports:
            - ${SERVER_PORT}:80
        volumes:
            - ./docker/nginx:/etc/nginx/conf.d
            # - ./docker/nginx:/etc/nginx/sites-available/default
            # - ./docker/nginx:/etc/nginx/sites-enabled/default
            - ./docker/logs/:/var/log/nginx/
            - ./docker/www:/var/www/html
        restart: always

    php:
        # image: php:7.2-fpm
        build:
            context: ./docker/php
        container_name: php-fpm
        ports:
            - 127.0.0.1:${PHP_PORT}:9000
        environment:
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./docker/www:/var/www/html
        depends_on:
            - mysql
        restart: always

    mysql:
        image: mysql:5.7
        container_name: mysql
        ports:
            - 127.0.0.1:${DB_PORT}:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./docker/db:/docker/db
            - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
        restart: always
