---
- hosts: web3
  become: yes
  vars: 
    DB_NAME: "db_test" 
  tasks:
    - name: Check Version OS
      block: # For Debian
      - name: Add Docker GPG apt Key
        apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present

      - name: Add Docker Repository
        apt_repository:
          repo: deb https://download.docker.com/linux/ubuntu bionic stable
          state: present

      - name: Update apt and install docker-ce
        apt: update_cache=yes name=docker-ce state=latest

      - name: Update apt and install docker-compose
        apt: update_cache=yes name=docker-compose state=latest

      - name: Build docker-compose.yml
        shell: docker-compose build

      - name: Run docker-compose.yml
        shell: docker-compose up -d 

      - name: Import DB
        shell: docker exec -T mysql mysql -uroot -proot {{ DB_NAME }} < dump.sql
        ignore_errors: yes #
      when: ansible_os_family == "Debian"

    - name: Brake if OS non Debian family
      debug: msg="This works for OS Debian family" #
      when: ansible_os_family != "Debian"
